site_name: EdgarTools - Python Library for SEC Data Analysis
site_description: Access and analyze SEC filings, financial statements, insider trading, and investment fund data
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy

nav:
  - Home:
    - Overview: index.md
    - Why EdgarTools: why-edgartools.md
    - Installation: installation.md
    - Configuration: configuration.md
    - Quick Start: quickstart.md
    - Quick Reference: quick-guide.md
  - How to Guides:
    - Filings:
      - "Working with a Filing": guides/working-with-filing.md
      - "Search for Specific Filings": guides/searching-filings.md
      - "Filter Filings by Date/Type": guides/filtering-filings.md
      - "Access Filing Attachments": guides/filing-attachments.md
      - "Finding the most recent filings": guides/current-filings.md
    - Companies:
      - "Working with a company": guides/finding-companies.md
      - Getting company facts: guides/company-facts.md
      - Creating a Multi Year Financials Data Api: guides/multi-year-financial-data-api.md
      - Getting a list of company insiders: guides/company-insiders.md
      - Getting subsets of companies: company-subsets.md
    - Financial Analysis:
      - "Extract Financial Statements": guides/extract-statements.md
    - Advanced:
        - "Advanced Ranking Search": advanced-search.md
        - "Using Local Data Storage": guides/local-storage.md
        - "Using Cloud Storage": guides/cloud-storage.md
        - SSL Issues and Configuration: guides/ssl_verification.md
        - Parsing SGML: guides/sgml.md
  - XBRL and Financials:
    - Getting XBRL from Filings: getting-xbrl.md
    - Querying XBRL Facts: xbrl-querying.md
    - Getting footnotes from XBRL: guides/xbrl-footnotes.md
  - Data Objects:
    - Data Objects: data-objects.md
    - Insider Filings: insider-filings.md
    - ThirteenF Holding Reports: 13f-filings.md
  - Concepts:
    - "Understanding SEC Filings": concepts/sec-filings.md
    - "Understanding Data Objects": concepts/data-objects.md
  - API Reference:
    - Core Objects:
      - Company: api/company.md
      - Filing: api/filing.md
      - Filings: api/filings.md
      - XBRL: api/xbrl.md
  - AI Integration: ai-integration.md

  - Resources:
    - "Common Issues & Solutions": resources/troubleshooting.md
    - "Performance Best Practices": resources/performance.md
    - "SEC Rate Limits & Compliance": resources/sec-compliance.md

  - Contributing: contributing.md


